### ISSUE TITLE
Performance regression / editor stall with Unity 2022 LTS

### ISSUE THREAD

**Issue by kidkwazine** [Cyanilux/ShaderGraphVariables#4]
Hey there! 

I'm getting some editor stalls after upgrading a project from Unity 2021 LTS to the (newly released) Unity 2022 LTS. 

It _seems_ to occur within the editor update / 'CheckforGraphs' method when the Shadergraph window is refocused. 

I enabled the debug messages in the code to see what's going on during the stall to see if I could find a fix to no avail —it reads the editor window as switched, clears the variable dictionary, registers each one back, and then handles the linking. This seems like what it should normally be doing, yea? It seems to be wildin' with GC allocations for a single frame when editor functionality returns. 

Profiler screenshot, if it's of any help!

![Unity_kL0](https://github.com/Cyanilux/ShaderGraphVariables/assets/16472141/959f81c0-dd7c-4952-90b0-384f3429b54c)

### Currently Using:
- Unity 2022.3.1f1 LTS
- Shadergraph 14.0.8
- Shader Graph Variables 1.0.1

P.S. This is an invaluable QoL utility for Shadergraph so thanks for making it 🌞

**Comment by Cyanilux** [comment]
Hmm yeah, I noticed this too. It seems to be caused by `ValidateGraph()` - which I'm mostly calling since the SG source code seems to do it too when things are changed.

When removing that it stops the editor stalling, and everything appears to be working fine too - so I'll probably just leave that function out.

Will fix a few other bits and update package soon.

**Comment by Cyanilux** [comment]
Main branch has now been updated~ hopefully no new issues appear with the changes 😄

**Comment by kidkwazine** [comment]
This seems to resolve it on my end, as well! 

You rock! <3
